Added pause functionality for load cell callibration modals.
StudentOrganisationForAerospaceResearch/RocketControlUnit pull request #35
Opened 2024-10-26 17:57 UTC by connellr023

Modal state when configuring individual load cells is saved if the "pause" button is pressed. Clicking "cancel" will erase its state, effectively resetting the modal sequence.

I created a new component called `PausablePromptModal` which still needs styled. @Jgerbrandt, are you able to provide the tailwind for that?

2024-10-27 15:00 UTC, Jgerbrandt requested changes
For the calibration modals we just use skeletonUI you can find out how to use them here

https://www.skeleton.dev/utilities/modals

2024-10-27 15:02 UTC, Jgerbrandt commented
@EtSubas Any backend changes needed for pause?

2024-10-31 01:12 UTC, connellr023 commented
> For the calibration modals we just use skeletonUI you can find out how to use them here
> 
> https://www.skeleton.dev/utilities/modals

I added the tailwind to my modal component. it is properly styled now

2024-11-02 16:17 UTC, Jgerbrandt submitted a review, later dismissed

2024-11-02 17:47 UTC, EtSubas submitted a review, later dismissed
Looks good on the backend as well should work as normal

2024-11-02 19:53 UTC, Jgerbrandt approved these changes

2024-11-02 19:55 UTC, merged